# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

antibody_model_monophasic_cpp <- function(i, t1, b, exposure_histories, biomarker_states, kinetics_parameters, biomarker_map) {
    .Call(`_serosim_antibody_model_monophasic_cpp`, i, t1, b, exposure_histories, biomarker_states, kinetics_parameters, biomarker_map)
}

antibody_model_biphasic_cpp <- function(i, t1, b, exposure_histories, biomarker_states, kinetics_parameters, biomarker_map) {
    .Call(`_serosim_antibody_model_biphasic_cpp`, i, t1, b, exposure_histories, biomarker_states, kinetics_parameters, biomarker_map)
}

subset_dataframe_integer <- function(mydata, condition_vector, return_vector, condition) {
    .Call(`_serosim_subset_dataframe_integer`, mydata, condition_vector, return_vector, condition)
}

subset_dataframe_numeric_twice <- function(x, condition_vector1, condition_vector2, return_vector, condition1, condition2) {
    .Call(`_serosim_subset_dataframe_numeric_twice`, x, condition_vector1, condition_vector2, return_vector, condition1, condition2)
}

subset_dataframe_numeric <- function(mydata, condition_vector, return_vector, condition) {
    .Call(`_serosim_subset_dataframe_numeric`, mydata, condition_vector, return_vector, condition)
}

subset_dataframe_char <- function(mydata, condition_vector, return_vector, condition) {
    .Call(`_serosim_subset_dataframe_char`, mydata, condition_vector, return_vector, condition)
}

get_cube_slices <- function(x, indices) {
    .Call(`_serosim_get_cube_slices`, x, indices)
}

get_mat_cols <- function(x, indices) {
    .Call(`_serosim_get_mat_cols`, x, indices)
}

sum_arma_na_rm <- function(X) {
    .Call(`_serosim_sum_arma_na_rm`, X)
}

