# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Monophasic antibody boosting-waning model Rcpp implementation
#' 
#' @description Identical to \code{\link{antibody_model_monophasic}}, but implemented in Cpp
#'
#' @inheritParams antibody_model_monophasic
#'
#' @return Biomarker quantity at the specified time point
#' @export
#' @family antibody_models
#'
#' @examples
#' tmp_pars <- list()
#' tmp_pars[[1]] <- draw_parameters_fixed_fx(1,1,1,NULL, NULL, example_model_pars_numeric)
#' antibody_model_monophasic_cpp(1,1,1,example_immune_histories_wide, example_biomarker_states_wide, 
#' tmp_pars, example_biomarker_map_numeric)
antibody_model_monophasic_cpp <- function(i, t1, b, immune_histories, biomarker_states, kinetics_parameters, biomarker_map) {
    .Call(`_serosim_antibody_model_monophasic_cpp`, i, t1, b, immune_histories, biomarker_states, kinetics_parameters, biomarker_map)
}

#' Biphasic antibody boosting-waning model Rcpp implementation
#' 
#' @description Identical to \code{\link{antibody_model_biphasic}}, but implemented in Cpp
#'
#' @inheritParams antibody_model_monophasic
#'
#' @return Biomarker quantity at the specified time point
#' @family antibody_models
#' @export
#' @examples
#' tmp_pars <- list()
#' tmp_pars[[1]] <- draw_parameters_fixed_fx(1,1,1,NULL, NULL, example_model_pars_numeric)
#' antibody_model_biphasic_cpp(1,1,1,example_immune_histories_wide, example_biomarker_states_wide, 
#' tmp_pars, example_biomarker_map_numeric)
antibody_model_biphasic_cpp <- function(i, t1, b, immune_histories, biomarker_states, kinetics_parameters, biomarker_map) {
    .Call(`_serosim_antibody_model_biphasic_cpp`, i, t1, b, immune_histories, biomarker_states, kinetics_parameters, biomarker_map)
}

